from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog


class BarkodList(QDialog):
    def __init__(self):
        super().__init__()
        self.icon = QtGui.QIcon()
        self.icon.addPixmap(QtGui.QPixmap("img/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_icon = QtGui.QIcon('img/delete.png')
        self.setWindowIcon(self.icon)
        self.setObjectName("self")
        self.resize(362, 335)
        self.setMinimumSize(QtCore.QSize(362, 335))
        self.setMaximumSize(QtCore.QSize(362, 335))
        self.setBaseSize(QtCore.QSize(362, 335))
        self.setStyleSheet("QLineEdit{\n"
                           "border:0px;\n"
                           "background:transparent\n"
                           "}")
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(18, 53, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self)
        self.label_5.setGeometry(QtCore.QRect(18, 253, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setGeometry(QtCore.QRect(18, 95, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.line_2 = QtWidgets.QFrame(self)
        self.line_2.setGeometry(QtCore.QRect(14, 75, 331, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setGeometry(QtCore.QRect(18, 131, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.line_7 = QtWidgets.QFrame(self)
        self.line_7.setGeometry(QtCore.QRect(13, 194, 331, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_6 = QtWidgets.QFrame(self)
        self.line_6.setGeometry(QtCore.QRect(16, 275, 331, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_3 = QtWidgets.QFrame(self)
        self.line_3.setGeometry(QtCore.QRect(14, 118, 331, 10))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self)
        self.line_4.setGeometry(QtCore.QRect(14, 155, 331, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_8 = QtWidgets.QLabel(self)
        self.label_8.setGeometry(QtCore.QRect(17, 212, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.line_5 = QtWidgets.QFrame(self)
        self.line_5.setGeometry(QtCore.QRect(14, 234, 331, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line = QtWidgets.QFrame(self)
        self.line.setGeometry(QtCore.QRect(14, 34, 331, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(18, 17, 47, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_7 = QtWidgets.QLabel(self)
        self.label_7.setGeometry(QtCore.QRect(17, 168, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self)
        self.label_6.setGeometry(QtCore.QRect(18, 290, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lineEditTarih = QtWidgets.QLineEdit(self)
        self.lineEditTarih.setGeometry(QtCore.QRect(180, 10, 161, 25))
        self.lineEditTarih.setReadOnly(True)
        self.lineEditTarih.setObjectName("lineEditTarih")
        self.lineEditMevsim = QtWidgets.QLineEdit(self)
        self.lineEditMevsim.setGeometry(QtCore.QRect(180, 50, 161, 25))
        self.lineEditMevsim.setReadOnly(True)
        self.lineEditMevsim.setObjectName("lineEditMevsim")
        self.lineEditUrunKodu = QtWidgets.QLineEdit(self)
        self.lineEditUrunKodu.setGeometry(QtCore.QRect(180, 90, 161, 25))
        self.lineEditUrunKodu.setReadOnly(True)
        self.lineEditUrunKodu.setObjectName("lineEditUrunKodu")
        self.lineEditMagazaKodu = QtWidgets.QLineEdit(self)
        self.lineEditMagazaKodu.setGeometry(QtCore.QRect(180, 130, 161, 25))
        self.lineEditMagazaKodu.setReadOnly(True)
        self.lineEditMagazaKodu.setObjectName("lineEditMagazaKodu")
        self.lineEditMagazaUrunKodu = QtWidgets.QLineEdit(self)
        self.lineEditMagazaUrunKodu.setGeometry(QtCore.QRect(180, 170, 161, 25))
        self.lineEditMagazaUrunKodu.setReadOnly(True)
        self.lineEditMagazaUrunKodu.setObjectName("lineEditMagazaUrunKodu")
        self.lineEditBeden = QtWidgets.QLineEdit(self)
        self.lineEditBeden.setGeometry(QtCore.QRect(180, 210, 161, 25))
        self.lineEditBeden.setReadOnly(True)
        self.lineEditBeden.setObjectName("lineEditBeden")
        self.lineEditRenk = QtWidgets.QLineEdit(self)
        self.lineEditRenk.setGeometry(QtCore.QRect(180, 250, 161, 25))
        self.lineEditRenk.setReadOnly(True)
        self.lineEditRenk.setObjectName("lineEditRenk")
        self.lineEditKumasTuru = QtWidgets.QLineEdit(self)
        self.lineEditKumasTuru.setGeometry(QtCore.QRect(180, 290, 161, 25))
        self.lineEditKumasTuru.setReadOnly(True)
        self.lineEditKumasTuru.setObjectName("lineEditKumasTuru")

        self.label_2.setText("Mevsim")
        self.label_5.setText("Renk")
        self.label_3.setText("Ürün Kodu")
        self.label_4.setText("Mağaza Kodu")
        self.label_8.setText("Beden")
        self.label.setText("Tarih")
        self.label_7.setText("Mağaza Ürün Kodu")
        self.label_6.setText("Kumaş Türü")
        QtCore.QMetaObject.connectSlotsByName(self)
